### ISSUE TITLE
If condtions are not getting pretty printed

### ISSUE THREAD

**Issue by kiran-rachamalla** [fmabap/AMDP_Pretty_Printer#21]
I tried to pretty print the conditions in report but it is not getting pretty printed
attached the screenshot. 
<img width="925" alt="pretty print" src="https://github.com/fmabap/AMDP_Pretty_Printer/assets/3682147/1626f584-07e7-4e71-8cb6-60257187c024">

**Comment by fmabap** [comment]
Hi Kiran,
if you want to test the AMDP Pretty Printer with the Test Tool, then you have to add an AMDP test method. You can use the button "Add Test Method" for it.

Please be aware that the AMDP Pretty Printer does not remove manually set line breaks (like the then in the screenshot below) and that spaces sometimes do not appear correctly in the result longtext control (based on the font that SAP uses). But you can copy the result to Notepad to see it well formatted.

<img width="1448" alt="image" src="https://github.com/fmabap/AMDP_Pretty_Printer/assets/101019006/1d7c553a-2e89-4e25-9c4f-fe364aa2da83">


Best regards
Frank

**Comment by fmabap** [comment]
Closed, because of no response.
